### ISSUE TITLE
Question about running multiple inference with TensorRT

### ISSUE THREAD

**Issue by ghimireadarsh** [deepcam-cn/yolov5-face#63]
I ran the tensorRT Engine file for inference successfully, and the performance is amazing compared to default in Jetson TX2 board. However, when I try to run infer using the same loaded engine file it shows wrong results as well as the inference time has increased. Could you please recommend or guide on how to apply trt engine file for multiple inference.
Thanks.

**Comment by bobo0810** [comment]
@ghimireadarsh  What does multiple inference mean?

**Comment by ghimireadarsh** [comment]
@bobo0810 I want to make prediction on sequence of images

**Comment by bobo0810** [comment]
> _Correcting my previous comment_
> @bobo0810 How can I make inferences for sequence of images?

batch=1, apply the "for" loop.
batch=N, explore the batch dimension variability of Pytorch-> onNx ->TensorRT.

**Comment by ghimireadarsh** [comment]
> > _Correcting my previous comment_
> > @bobo0810 How can I make inferences for sequence of images?
> 
> batch=1, apply the "for" loop.
> batch=N, explore the batch dimension variability of Pytorch-> onNx ->TensorRT.

I tried the for loop way and I would prefer to go with for loop way because I cannot have batch for my application. 
However I keep on getting the following error when I run the inference on second data.

```shell
[TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (925) - Cuda Error in NCHWToNCHHW2: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
```

**Comment by ghimireadarsh** [comment]
I have solved the issue by creating the context and then pushing the context for operation which allows the inference with sequence of images. Later, after doing required number of inferences closing the context properly which results in proper execution of code.

**Comment by Tetsujinfr** [comment]
Hi @ghimireadarsh 
I see you are using a jetson to run the tensorrt version of the model.
I have very slow performance (24seconds) for the after_process() part of the trt inference from yolo_trt_model.py, do you not have the same issue?

**Comment by Tetsujinfr** [comment]
Ok so the speed issue on my end might be due to the first inference run, or maybe due to some pytorch/cuda bad combination.
For now I have increased a bit the speed by generating tensor directly on gpu rather than doing a cpu to gpu copy.

@ghimireadarsh can you share some more details on the context you created for the for loop you implemented? I am going through similar memory issues (NCHWToNCHHW2: 400 () by implementing a naive for loop.
thanks vm

**Comment by ghimireadarsh** [comment]
@Tetsujinfr the code that has been written here directly runs by creating context from engine file so it only works for the first input that you pass. So for it to work for multiple inputs you first you need to make context at first using `make_context()`. Then pass the input specify context using push command `context.push()` on every call.

**Comment by Tetsujinfr** [comment]
Thanks. I am going to try that approach.

Do you have good performance on your jetson for the after_process() part of the inference? The tensor([8,80,16].to(device) takes an enormous amount of time on mine for some reason, which seems crazy given the small size of the tensor.

If you do not have this issue, can you please share your pytorch, cuda and numpy versions pls?
Thanks

**Comment by Tetsujinfr** [comment]
Ok so after some pain and debugging I got the tensorrt running properly on a for loop of inputs.

A bit disappointed for now, the speed-up on a 640px input frame inferencing on my Jetson NX is 2x to 3x (which is great, but far from the ratios mentioned on the readme of the repo).

Also, deploying the trt engine is adding a lot of rigidity, e.g. hard resolution per trt engine, slow pre and post procesing with the current trt code at least.
Maybe this is due to my NX setup. Maybe there is room for improvement on refactoring the trt code further. But for now, end to end on the NX, the performance is similar if not worse with the trt version due to all the slow steps before/after inferencing.

@ghimireadarsh , what type of speed up do you achieve with tensorrt vs .pt model on your jetson ? What about the end to end fps, say for yolov5s-face ?

**Comment by ghimireadarsh** [comment]
@Tetsujinfr I am sorry that I do not have access to my jetson 
presently so I am not able to give the exact and complete detail for now. As i remember i had used the smallest model yolov5-n0.5 and was getting Fps of model inferencing of upto 145 FPS on 256x256 input video and around 60-70 FPS on 640x640 input. 
I do not have info on end to end FPS as I remember my camera frame rate was 30 FPS so the end to end was somewhat around 30FPS too. I will check that and give you update soon I have access to my board. 
In my case I have to say that the trt version had improved the performance significantly.

**Comment by alient12** [comment]
> @Tetsujinfr the code that has been written here directly runs by creating context from engine file so it only works for the first input that you pass. So for it to work for multiple inputs you first you need to make context at first using `make_context()`. Then pass the input specific context using push command `context.push()` on every call.

THX, your hint helped me find the problem. I was looking for an example code of what you mentioned, and I found this, hope this help the others.
https://forums.developer.nvidia.com/t/how-to-use-tensorrt-by-the-multi-threading-package-of-python/123085/8

**Comment by zts2002** [comment]
can you show me your main.py program?thank you very , because i dont know how to inference with my jetson nano's /dev/video camera
